### ISSUE TITLE
Design crunch

### ISSUE THREAD

**Issue by helveticade** [SpiderOak/Encryptr#197]
Cool checklist:
- [x] Touch friendly menu
- [x] Add branding
- [x] Redo splash
- [x] Assets for touch friendly menu
- [x] Recolour app
- [x] New typeface
- [x] Redesign dialog boxes
- [x] Better transitions between screens in the app
- [x] Restyle Item view
- [x] Restyle new item view
- [x] Better loading animation
- [x] Redo settings page
- [x] Fixed search
- [x] Better empty state
- [x] Restyle error messages
- [x] Restyle login
- [x] Restyle search results
- [x] Restyle notification box
- [x] New 🍞s.

**Comment by jchan-scc** [comment]
also, 
- settings for how often to sync the index (everytime it logs in seems like a lot), 
- settings for how long before logging out

**Comment by devgeeks** [comment]
@helveticade 

Still needed:

- [ ] Save button asset
- [ ] Shadow definition for the "big add button"

**Comment by helveticade** [comment]
@jchan-scc Noted! we'll be working on these post–design crunch!

**Comment by helveticade** [comment]
- [ ] New alignment issue with login boxs and the background grid.
- [ ] Redo error messaging with better wording
- [ ] Redo edit pen icon
- [ ] Integrate revised-coloured icons
- [ ] Add support links
- [ ] Revise padding on 'Add new...' drawer
- [ ] Revise padding on dialog box buttons
- [ ] Adjust padding on Item text field titles
- [ ] Bold Item Types on password list view.
- [ ] Center load spinner.
- [ ] Add image to empty state

**Comment by devgeeks** [comment]
Finished

**Comment by helveticade** [comment]
🎉
