### ISSUE TITLE
No Logout

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/Encryptr#236]
Is the loss of a logout function in 2.0.0 intentional?

**Comment by devgeeks** [comment]
It's not gone... it's in the settings.. and called "Lock Encryptr".

@helveticade is again to blame.

![iphone 6 - iphone 6 ios 9 0 13a340 2015-11-24 09-09-22](https://cloud.githubusercontent.com/assets/554999/11351507/2c68043a-928b-11e5-8006-d9445028f169.png)

**Comment by helveticade** [comment]
I'm interested to see whether the change of language is confusing or not. The intentions are definitely different, especially as we move Encryptr towards re-authentication when re-opening, rather than sign in/out completely.

**Comment by reneelynn** [comment]
I definitely viewed "Lock Encrytpr" as a reauthentication setting as opposed to a sign out/in setting. 
Many of these questions are because I wasn't informed of the changes happening so I have to make sure each change is intentional.
