### ISSUE TITLE
Logging In - mobile

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/Encryptr#239]
To login to an established account, enter "Username" and "Passphrase".

in landscape view in mobile you cannot see "passphrase" unless you minimize your keyboard.

**Comment by daviddahl** [comment]
is this on iOS as well as android? We can build iOS to not allow landscape view

**Comment by reneelynn** [comment]
yes

**Comment by reneelynn** [comment]
resolved in iOS in 2.0.0-final

**Comment by devgeeks** [comment]
I made iPhone locked to portrait, but iPad allows landscape.
