### ISSUE TITLE
Search Doesn't Search Many Fields

### ISSUE THREAD

**Issue by dgiffin** [SpiderOak/Encryptr#251]
Seems that the search field doesn't search any fields other than the Label - would be useful to be able to search on Notes etc too.

**Comment by devgeeks** [comment]
That's not currently possible. Try to think of the search as for of a filter. It filters the list of entries. The actual entries are not loaded at that time.

**Comment by dgiffin** [comment]
Ok, thanks for the explanation, sorry for misunderstanding :-)

**Comment by devgeeks** [comment]
Not a problem. I mean, a full real text search would be great, but that would be a big change.
