### ISSUE TITLE
missing Encryptr.js to run with nw.js

### ISSUE THREAD

**Issue by yotamN** [SpiderOak/Encryptr#279]
I try to run the program from source to add features but I can't run it, I get this error message:
![screenshot from 2016-11-26 14-58-16](https://cloud.githubusercontent.com/assets/5249239/20640530/ca3260d2-b3e8-11e6-9e68-a03df230d009.png)

The file is in .gitignore so maybe you accidentally ignored it? I can't run the program without it

**Comment by yotamN** [comment]
Oh I see I need to generate it, sorry

**Comment by devgeeks** [comment]
Glad you figured it out :)
