### ISSUE TITLE
Passwords have stopped syncing Moto G5+ Android 7.0

### ISSUE THREAD

**Issue by convct** [SpiderOak/Encryptr#297]
Moto G5+ Android 7.0
Android security patch level 1st Jan 2017
Kernel Feb 6 20108 2018
Build number NPN25.137.33
Stopped syncing around 2 weeks ago I think. I have not yet checked updates installed.
if there is anything I can do to help test this please let me know.

**Comment by Samahedron** [comment]
I believe this is a duplicate of issue #292

**Comment by convct** [comment]
Yes you're quite right., I'll move out there and close this.
